spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 121455607068-6hel0glh1tk84r75n21a03tbc4tpel9b.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

  mvc:
    hidden-method:
      filter:
        enabled: true


logging:
  level:
    com.example: DEBUG